name: flutter_printer_plus
description: flutter 端 【小票、标签】打印能力实现，直接将 flutter widget 转图像数据进行打印。
version: 0.0.1+2
homepage: https://github.com/liyufengrex/flutter_printer_plus.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.3"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.12
  image: ^3.0.2
  isolates: ^3.0.3
  esc_utils: ^0.0.1
  tsc_utils: ^0.0.1
  android_usb_printer: ^0.0.1
  print_image_generate_tool: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
