name: flutter_printer_plus
description: flutter flutter_printer_plus
version: 1.0.1
homepage: https://github.com/liyufengrex/flutter_printer_plus.git

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.5.3"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.12
  image: ^3.0.2
  isolates: ^3.0.3
  esc_utils: ^0.0.1
  tsc_utils: ^0.0.1
  android_usb_printer:
    git:
      url: git@github.com:Aaron51FX/android_usb_printer.git
      ref: master
  windows_usb_printer:
    git:
      url: git@github.com:Aaron51FX/windows_usb_printer.git
  print_image_generate_tool: ^0.0.2
  r_get_ip:
    git:
      url: git@github.com:Aaron51FX/r_get_ip.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
